DW: false
backdoor: true
batch_size: 128
config: configs/draft.yaml
dataroot: data
dataset: CIFAR100
dataset_path: ./data/
debug_mode: 0
first_split_size: 100
gen_round: 1000
generating_lr_tri: 0.01
generating_lr_warmup: 0.1
gpuid:
- 2
- 3
- 4
- 5
- 6
- 7
l_inf_r: 0.06274509803921569
learner_name: CODAPrompt
learner_type: prompt
log_dir: outputs-bce/cifar-100/draft/coda-p
lr: 0.001
max_task: 1
memory: 0
model_name: vit_pt_imnet
model_type: zoo
momentum: 0.9
multi_test: 3
noise_path: ./outputs/cifar-100/attack/coda-p/triggers/repeat-1/task-trigger-gen/06-29-03_59_57.npy
noise_size: 224
noise_weight: 100
optimizer: Adam
oracle_flag: false
other_split_size: 0
overwrite: 1
patch_mode: add
poison_amount: 25
prompt_param:
- 100.0
- 8.0
- 0.0
rand_split: true
random_seed: 65
repeat: 1
schedule:
- 20
schedule_type: cosine
surrogate_epochs: 200
target_lab: 90
temp: 2.0
train_aug: true
train_batch_size: 350
upper_bound_flag: false
validation: false
warmup_round: 5
weight_decay: 0
workers: 4
