DW: false
backdoor: true
batch_size: 128
config: configs/attack.yaml
dataroot: data
dataset: CIFAR100
dataset_path: ./data/
debug_mode: 0
first_split_size: 10
gen_round: 1000
generating_lr_tri: 0.01
generating_lr_warmup: 0.1
gpuid:
- 0
- 1
- 2
- 3
- 4
- 6
- 7
l_inf_r: 0.06274509803921569
learner_name: DualPrompt
learner_type: prompt
log_dir: outputs-bce/cifar-100/poison-10-task-target-60-ns-100/dual-prompt
lr: 0.001
max_task: -1
memory: 0
model_name: vit_pt_imnet
model_type: zoo
momentum: 0.9
multi_test: 3
noise_path: /home/ubuntu/Thesis/outputs-bce/cifar-100/draft/coda-p/triggers/repeat-1/task-trigger-gen/target-60-noise_weight-100.npy
noise_size: 224
noise_weight: 100
optimizer: Adam
oracle_flag: false
other_split_size: 10
overwrite: 1
patch_mode: add
poison_amount: 25
prompt_param:
- 10.0
- 20.0
- 6.0
rand_split: false
random_seed: 65
repeat: 1
schedule:
- 20
schedule_type: cosine
surrogate_epochs: 200
target_lab: 60
temp: 2.0
train_aug: true
train_batch_size: 350
upper_bound_flag: false
validation: false
warmup_round: 5
weight_decay: 0
workers: 4
